

service: membership-aws-serverless-api

provider:
  name: aws
  runtime: java8
  stage: dev
  region: eu-central-1
  timeout: 50
  endpointType: regional
  environment:
    IS_OFFLINE: ${self:custom.isOffline}
    CONFIG_USERS_TABLE: ${self:custom.tableNames.users}
    CONFIG_DYNAMODB_ENDPOINT: ${self:custom.endpoints.dynamodb-url}
  iamRoleStatements:
   - Effect: "Allow"
     Action:
       - "dynamodb:*"
     Resource: "*"
custom:
  tableNames:
    users: 'aige-user'
  endpoints:
    dynamodb-url: 'http://localhost:8000'
  isOffline: true
  dynamodb:
    start:
      migrate: true
      seed: true
    stages:
      - dev
    seed:
      domain:
        sources:
          - table: aige-user
            rawsources: [src/main/resources/user2/testdata.json]
      

package:
  artifact: 'target/${self:service}-${self:provider.stage}.jar'
  exclude:
    - testdata/**
    - node_modules/**  
    
functions:
  - ${file(src/main/resources/user/lambdas.yml)}
resources:
  - ${file(src/main/resources/user/dynamodb.yml)}

plugins:
  - serverless-offline
  - serverless-dynamodb-local
